# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='example.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rexample.proto\x12\x07\x65xample\"#\n\x0fQuestionRequest\x12\x10\n\x08question\x18\x01 \x01(\t\" \n\x0eQuestionAnswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\x1f\n\rSquareRequest\x12\x0e\n\x06number\x18\x01 \x01(\x03\"\x1a\n\x07Squared\x12\x0f\n\x07squared\x18\x01 \x01(\x03\x32R\n\x0e\x41nswersService\x12@\n\x0bsayQuestion\x12\x18.example.QuestionRequest\x1a\x17.example.QuestionAnswer2H\n\x0fSquaringService\x12\x35\n\tgetSquare\x12\x16.example.SquareRequest\x1a\x10.example.Squaredb\x06proto3'
)




_QUESTIONREQUEST = _descriptor.Descriptor(
  name='QuestionRequest',
  full_name='example.QuestionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='question', full_name='example.QuestionRequest.question', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=61,
)


_QUESTIONANSWER = _descriptor.Descriptor(
  name='QuestionAnswer',
  full_name='example.QuestionAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='example.QuestionAnswer.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=95,
)


_SQUAREREQUEST = _descriptor.Descriptor(
  name='SquareRequest',
  full_name='example.SquareRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='example.SquareRequest.number', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=128,
)


_SQUARED = _descriptor.Descriptor(
  name='Squared',
  full_name='example.Squared',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='squared', full_name='example.Squared.squared', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['QuestionRequest'] = _QUESTIONREQUEST
DESCRIPTOR.message_types_by_name['QuestionAnswer'] = _QUESTIONANSWER
DESCRIPTOR.message_types_by_name['SquareRequest'] = _SQUAREREQUEST
DESCRIPTOR.message_types_by_name['Squared'] = _SQUARED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QuestionRequest = _reflection.GeneratedProtocolMessageType('QuestionRequest', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONREQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.QuestionRequest)
  })
_sym_db.RegisterMessage(QuestionRequest)

QuestionAnswer = _reflection.GeneratedProtocolMessageType('QuestionAnswer', (_message.Message,), {
  'DESCRIPTOR' : _QUESTIONANSWER,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.QuestionAnswer)
  })
_sym_db.RegisterMessage(QuestionAnswer)

SquareRequest = _reflection.GeneratedProtocolMessageType('SquareRequest', (_message.Message,), {
  'DESCRIPTOR' : _SQUAREREQUEST,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.SquareRequest)
  })
_sym_db.RegisterMessage(SquareRequest)

Squared = _reflection.GeneratedProtocolMessageType('Squared', (_message.Message,), {
  'DESCRIPTOR' : _SQUARED,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.Squared)
  })
_sym_db.RegisterMessage(Squared)



_ANSWERSSERVICE = _descriptor.ServiceDescriptor(
  name='AnswersService',
  full_name='example.AnswersService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=240,
  methods=[
  _descriptor.MethodDescriptor(
    name='sayQuestion',
    full_name='example.AnswersService.sayQuestion',
    index=0,
    containing_service=None,
    input_type=_QUESTIONREQUEST,
    output_type=_QUESTIONANSWER,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ANSWERSSERVICE)

DESCRIPTOR.services_by_name['AnswersService'] = _ANSWERSSERVICE


_SQUARINGSERVICE = _descriptor.ServiceDescriptor(
  name='SquaringService',
  full_name='example.SquaringService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=242,
  serialized_end=314,
  methods=[
  _descriptor.MethodDescriptor(
    name='getSquare',
    full_name='example.SquaringService.getSquare',
    index=0,
    containing_service=None,
    input_type=_SQUAREREQUEST,
    output_type=_SQUARED,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SQUARINGSERVICE)

DESCRIPTOR.services_by_name['SquaringService'] = _SQUARINGSERVICE

# @@protoc_insertion_point(module_scope)
